SECRET_PATH: "conf/.secrets.yaml"
# Default environment. Overridden if specified through environment variable (prefixed by conf.IDPAY_ENV_VAR_PREFIX current value)
TARGET_ENV: "uat"
API_KEY_HEADER: "Ocp-Apim-Subscription-Key"
default_timeout: 5000
long_timeout: 60000
iso_date_format: '%Y-%m-%dT%H:%M:%S.000%z'
base_path:
  IO: "https://api-io.uat.cstar.pagopa.it"
  CSTAR: "https://api.uat.cstar.pagopa.it"
  RTD: "https://api.uat.cstar.pagopa.it"
  IDPAY:
    internal: "https://uat01.idpay.internal.uat.cstar.pagopa.it"
IDPAY:
  domain: "/idpay"
  endpoints:
    onboarding:
      path: "/onboarding"
      initiative: "/onboarding/initiative"
      enrollment:
        start_path: "/hb/wallet"
        end_path: "/instruments"
        unsubscribed_message: "You are unsubscribed at this initiative!"
        not_active_for_user_message: "The requested initiative is not active for the current user!"
        invalid_fc_message: 'Fiscal code not valid!'
      consent: "/onboarding/consent"
      status: '/status'
      iban:
        start_path: "/wallet"
        end_path: "/iban"
        unknown_psp: "UNKNOWN_PSP"
      unsubscribed_message: 'Unsubscribed to initiative'
      unsubscribed_error_details: 'GENERIC_ERROR'
    wallet:
      path: '/wallet'
      end_path: '/instruments'
      unsubscribe: '/unsubscribe'
      statuses:
        not_refundable: 'NOT_REFUNDABLE'
        not_refundable_only_instrument: 'NOT_REFUNDABLE_ONLY_INSTRUMENT'
        not_refundable_only_iban: 'NOT_REFUNDABLE_ONLY_IBAN'
        refundable: 'REFUNDABLE'
        unsubscribed: 'UNSUBSCRIBED'
    timeline:
      path: '/timeline'
      operations:
        onboarding: 'ONBOARDING'
        add_iban: 'ADD_IBAN'
        add_instrument: 'ADD_INSTRUMENT'
        delete_instrument: 'DELETE_INSTRUMENT'
        transaction: 'TRANSACTION'
        reversal: 'REVERSAL'
    rewards:
      path: '/idpayrewardnotification/idpay'
      force_reward: '/reward/notification/exports/start?notificationDateToSearch='
    statistics:
      path: '/idpayinitiativestatistics/idpay'
    payment:
      path: '/payment'
      internal_path: '/idpaypayment/idpay'
      qr_code:
        path: '/qr-code'
        merchant: '/merchant'
    transactions:
      path: '/idpaytransactions'
      merchant: '/merchant'
      portal: '/portal/initiatives'
      processed: '/transactions/processed'
      unprocessed: '/transactions'
  acquirer_id: 'PAGOPA'
RTD:
  domain: "/rtd"
  endpoints:
    transactions:
      path: "/csv-transaction"
      public_key: "/publickey"
      SAS_token: "/rtd/sas"
    pagopastorage: "/pagopastorage"
    payment_instrument_manager:
      path: '/payment-instrument-manager'
      salt: '/salt'
      version: '/v3'
    mock_io:
      login: "/mock-io/login"
      user: "/mock-io/user"
initiatives:
  not_started:
    message: 'The initiative has not yet begun'
    details: 'INITIATIVE_NOT_STARTED'
  cashback_like:
    id: 'CASHBACK_LIKE'
    cashback_percentage: 30.22
    budget_per_citizen: 51.5
    fruition_start: '2023-03-13T00:00:00.000+01:00'
    fruition_end: '2099-03-13T22:59:59.000Z'
  complex:
    id: 'COMPLEX'
    cashback_percentage: 100
    min_trx_number: 2
    max_trx_number: 3
    min_trx_amount: 1
    max_trx_amount: 2000
    daily_budget: 5000
    budget_per_citizen: 100
    mcc_whitelist: [ '0743', '0744', '0763', '0742', '1353', '0780' ]
    fruition_end: '2099-03-31T22:59:59.000Z'
  timeframes:
    id: 'TIMEFRAMES'
    flat_cashback_amount: 5.01
    min_trx_number: 2
    max_trx_number: 3
    min_trx_amount: 501
    max_trx_amount: 200001
    daily_budget: 400002
    budget_per_citizen: 100
    fruition_start: '2023-04-17T00:00:00.000+01:00'
    fruition_end: '2099-04-17T22:59:59.000Z'
  Scontoditipo1:
    id: 'PILOT'
    cashback_percentage: 100
    budget_per_citizen: 300
    min_age: 18
    max_age: 35
    fruition_start: '2023-05-22T00:00:00.000+02:00'
    fruition_end: '2024-05-22T23:59:59.000+02:00'
  Scontoditipo6:
    id: 'SCONTOTIPO6'
    cashback_percentage: 87.12
    budget_per_citizen: 99.9
    min_age: 19
    max_trx_number: 1
    fruition_start: '2023-06-30T00:00:00.000+02:00'
    fruition_end: '2026-05-29T23:59:59.000+02:00'
  Scontoditipo8:
    id: 'SCONTOTIPO8'
    cashback_percentage: 100
    budget_per_citizen: 300
    min_trx_amount: 11.15
    max_trx_amount: 100
    daily_budget: 50
    max_age: 30
    fruition_start: '2023-07-20T00:00:00.000+02:00'
    fruition_end: '2024-05-30T23:59:59.000+02:00'
