SECRET_PATH: "conf/.secrets.yaml"
# Default environment. Overridden if specifies through environment variable (prefixed by conf.IDPAY_ENV_VAR_PREFIX current value)
TARGET_ENV: "uat"
API_KEY_HEADER: "Ocp-Apim-Subscription-Key"
