SECRET_PATH: "conf/.secrets.yaml"
# Default environment. Overridden if specified through environment variable (prefixed by conf.IDPAY_ENV_VAR_PREFIX current value)
TARGET_ENV: "uat"
API_KEY_HEADER: "Ocp-Apim-Subscription-Key"
base_path:
  IO: "https://api-io.uat.cstar.pagopa.it"
  CSTAR: "https://api.uat.cstar.pagopa.it"
  RTD: "https://api.uat.cstar.pagopa.it"
BPD:
  domain: "/bpd"
  endpoints:
    login: "/pagopa/api/v1/login"
    user: "/pagopa/api/v1/user"
IDPAY:
  domain: "/idpay"
  endpoints:
    onboarding:
      path: "/onboarding"
      initiative: "/onboarding/initiative"
      enrollment:
        start_path: "/hb/wallet"
        end_path: "/instruments"
        unsubscribed_message: "You are unsubscribed at this initiative!"
      consent: "/onboarding/consent"
      status: '/status'
      iban:
        start_path: "/wallet"
        end_path: "/iban"
    wallet:
      path: '/wallet'
      end_path: '/instruments'
      unsubscribe: '/unsubscribe'
      statuses:
        not_refundable: 'NOT_REFUNDABLE'
        not_refundable_only_instrument: 'NOT_REFUNDABLE_ONLY_INSTRUMENT'
        not_refundable_only_iban: 'NOT_REFUNDABLE_ONLY_IBAN'
        refundable: 'REFUNDABLE'
        unsubscribed: 'UNSUBSCRIBED'
    timeline:
      path: '/timeline'
      operations:
        add_iban: 'ADD_IBAN'
        add_instrument: 'ADD_INSTRUMENT'
        delete_instrument: 'DELETE_INSTRUMENT'
        transaction: 'TRANSACTION'
        reversal: 'REVERSAL'
RTD:
  domain: "/rtd"
  endpoints:
    transactions:
      path: "/csv-transaction"
      public_key: "/publickey"
      SAS_token: "/rtd/sas"
    pagopastorage: "/pagopastorage"
    payment_instrument_manager:
      path: '/payment-instrument-manager'
      salt: '/salt'
      version: '/v3'
initiatives:
  not_started:
    message: 'The initiative has not yet begun'
    details: 'INITIATIVE_NOT_STARTED'
  cashback_like:
    id: 'CASHBACK_LIKE'
    cashback_percentage: 30.22
    budget_per_citizen: 51.5
    fruition_end: '2099-03-13T22:59:59.000Z'
    unsubscribed_message: 'Unsubscribed to initiative'
    unsubscribed_error_details: 'GENERIC_ERROR'
