trigger: none

schedules:
  - cron: "0 6 * * 4" # Runs every Thursday at 06:00:00 UTC
    displayName: Scheduled Thursday run
    branches:
      include:
        - main
    always: true
  - cron: "0 9 * * 1" # Runs every Monday at 09:00:00 UTC
    displayName: Scheduled Monday run
    branches:
      include:
        - main
    always: true

variables:
  # Python version: 3.x
  pythonVersion: '3.x'
  # Folder name of this sub-repository
  working-dir: '.'
  # Project root folder
  projectRoot: $(System.DefaultWorkingDirectory)/$(working-dir)
  selfHostedAgentPool: 'cstar-uat-linux'
  TIME_OUT: 10

pool:
  vmImage: 'ubuntu-22.04'

parameters:
  - name: env
    displayName: Target Environment
    type: string
    default: uat
    values:
      - uat

  - name: tag
    displayName: Target tests tag (use unquoted "all" to run every un-skipped test)
    type: string
    default: ''

stages:
  - stage: Functional_tests
    dependsOn: [ ]
    pool:
      name: $(selfHostedAgentPool)
    jobs:
      - job: "Run_functional_tests"
        steps:
          - checkout: self
          - script: |
              python3 --version
              pip3 --version
            displayName: "Display Python version"
          - script: |
              python3 --version
              python3 -m pip install --user pipenv
              python3 -m pipenv sync
            displayName: "Install requirements"
          - task: DownloadSecureFile@1
            name: idpay_secrets
            displayName: 'Download IDPay secrets'
            inputs:
              secureFile: '.secrets.yaml'
          - script: |
              if [ -z "${{ parameters.tag }}" ] || [ "${{ parameters.tag }}" = "all" ]; then
                python3 -m pipenv run pytest --junitxml=tests/reports/pytest/junit.xml -vv
              else
                python3 -m pipenv run pytest --junitxml=tests/reports/pytest/junit.xml -vv -m "${{ parameters.tag }}"
              fi
            displayName: 'Run tests with Pytest'
            env:
              IDPAY_SECRET_PATH: $(idpay_secrets.secureFilePath)
              IDPAY_TARGET_ENV: ${{ parameters.env }}
            continueOnError: true
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'tests/reports/pytest/junit.xml'
              testRunTitle: 'Pytest Results'
              searchFolder: $(Build.SourcesDirectory)
              failTaskOnFailedTests: true
            continueOnError: true
