trigger:
  - main

variables:
  # Python version: 3.x
  pythonVersion: '3.x'

  # Folder name of this sub-repository
  working-dir: '.'

  # Project root folder
  projectRoot: $(System.DefaultWorkingDirectory)/$(working-dir)

  selfHostedAgentPool: 'cstar-uat-linux'

pool:
  vmImage: 'python:3.11-slim-buster@sha256:6d4b1a970e49fc2c37b4ad7b71ea4396a75abcd9d4f0331304743aba00932975'
  name: $(selfHostedAgentPool)

parameters:
  - name: env
    displayName: Target Environment
    type: string
    default: uat
    values:
      - uat

steps:
  - script: |
      python3 --version
      pip --version
    workingDirectory: $(projectRoot)
    displayName: "Display Python version"

  - script: |
      python3 -m pip install --upgrade pip
      python3 -m pip install --user virtualenv
      python3 -m virtualenv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
    workingDirectory: $(projectRoot)
    displayName: "Install requirements"

  - task: DownloadSecureFile@1
    name: idpay_secrets
    displayName: 'Download IDPay secrets'
    inputs:
      secureFile: '.secrets.yaml'

  - script: |
      source .venv/bin/activate
      IDPAY_SECRET_PATH=$(idpay_secrets.secureFilePath) IDPAY_TARGET_ENV="${{ parameters.env }}" pytest --junitxml=tests/reports/junit.xml -vv
    workingDirectory: $(projectRoot)
    displayName: 'Run tests with Pytest'

  - task: PublishTestResults@2
    condition: true
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'tests/reports/junit.xml'
      testRunTitle: 'Pytest Results'
      searchFolder: $(projectRoot)
      failTaskOnFailedTests: true
