trigger:
  - main

variables:
  # Python version: 3.x
  pythonVersion: '3.x'
  # Folder name of this sub-repository
  working-dir: '.'
  # Project root folder
  projectRoot: $(System.DefaultWorkingDirectory)/$(working-dir)
  selfHostedAgentPool: 'cstar-uat-deleteme-app'
  TIME_OUT: 10

pool:
  vmImage: 'ubuntu-22.04'

parameters:
  - name: env
    displayName: Target Environment
    type: string
    default: uat
    values:
      - uat

stages:
  - stage: Functional_tests
    dependsOn: []
    pool:
      name: $(selfHostedAgentPool)
    jobs:
      - job: prepare_config
        steps:
          - checkout: self
          - script: |
              ls -la
              pwd
              python3 --version
              pip3 --version
            displayName: "Display Python version"

          - script: |
              python3 --version
              python3 -m pip install --user virtualenv
              python3 -m virtualenv .venv
              source .venv/bin/activate
              pip install -r requirements.txt
            displayName: "Install requirements"

          - task: DownloadSecureFile@1
            name: idpay_secrets
            displayName: 'Download IDPay secrets'
            inputs:
              secureFile: '.secrets.yaml'
          - script: |
              ls -la
              pwd
              source .venv/bin/activate
              IDPAY_SECRET_PATH=$(idpay_secrets.secureFilePath) IDPAY_TARGET_ENV="${{ parameters.env }}" pytest --junitxml=tests/reports/junit.xml -vv -k test_send_single_transaction
            # workingDirectory: $(Build.SourcesDirectory)
            displayName: 'Run tests with Pytest'
          - task: PublishTestResults@2
            condition: true
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'tests/reports/junit.xml'
              testRunTitle: 'Pytest Results'
              searchFolder: $(Build.SourcesDirectory)
              failTaskOnFailedTests: true

      # - job: run_functional_tests
      #   condition: succeeded()
      #   dependsOn: [prepare_config]
      #   timeoutInMinutes: $[variables.TIME_OUT]
      #   steps:
      #     - script: |
      #         source .venv/bin/activate
      #         IDPAY_SECRET_PATH=$(idpay_secrets.secureFilePath) IDPAY_TARGET_ENV="${{ parameters.env }}" pytest --junitxml=tests/reports/junit.xml -vv
      #       workingDirectory: $(Build.SourcesDirectory)
      #       displayName: 'Run tests with Pytest'
      #     - task: PublishTestResults@2
      #       condition: true
      #       inputs:
      #         testResultsFormat: 'JUnit'
      #         testResultsFiles: 'tests/reports/junit.xml'
      #         testRunTitle: 'Pytest Results'
      #         searchFolder: $(Build.SourcesDirectory)
      #         failTaskOnFailedTests: true