uat:
  mauth:
    cert_base64: <CSTAR_CERTIFICATE_BASE64>
    key_base64: <CSTAR_PRIVATE_KEY_BASE64>
  api_key_issuer: <API_KEY_ISSUER_UAT>
  initiatives:
    not_started:
      id: <NOT_STARTED_ID>
      pgpan: <TEST_UAT_PGPAN>
    cashback_like:
      id: <CASHBACK_LIKE_ID>
