uat:
  mauth:
    cert_base64: <CSTAR_CERTIFICATE_BASE64>
    key_base64: <CSTAR_PRIVATE_KEY_BASE64>
  api_key:
    IDPAY_APP_ISSUER_PRODUCT: <API_KEY_ISSUER_UAT>
    RTD_API_Product: <API_KEY_RTD_UAT>
    RTD_Mock_API_Product: <API_KEY_RTD_MOCK_UAT>
    IDPAY_MIL_PRODUCT: <API_KEY_IDPAY_MIL_PRODUCT>
    IDPAY_MIN_INT_PRODUCT: <API_KEY_IDPAY_MININT_PRODUCT>
    PDV: <API_KEY_PDV>
  initiatives:
    Scontoditipo4:
      id: <SCONTO_DI_TIPO_4_ID>
    Scontoditipo5:
      id: <SCONTO_DI_TIPO_5_ID>
  pm:
    pub_key: <PM_PUBLIC_KEY>
  selfcare_info:
    test_institution:
      aud: 'idpay.welfare.pagopa.it'
      uid: <TEST_INSTITUTION_UID>
      orgId: <TEST_INSTITUTION_ORG_ID>
      orgName: <TEST_INSTITUTION_ORG_NAME>
      name: <TEST_INSTITUTION_NAME>
      familyName: <TEST_INSTITUTION_FAMILY_NAME>
      email: <TEST_INSTITUTION_EMAIL>
      orgVAT: <TEST_INSTITUTION_ORG_VAT>
      orgPartyRole: <TEST_INSTITUTION_ORG_PARTY_ROLE>
      orgRole: <TEST_INSTITUTION_ORG_ROLE>
    PagoPA:
      aud: 'idpay.welfare.pagopa.it'
      uid: <PAGOPA_AUD>
      orgId: <PAGOPA_ORG_ID>
      orgName: <PAGOPA_ORG_NAME>
      name: <PAGOPA_NAME>
      familyName: <PAGOPA_FAMILY_NAME>
      email: <PAGOPA_EMAIL>
      orgVAT: <PAGOPA_ORG_VAT>
      orgPartyRole: <PAGOPA_ORG_PARTY_ROLE>
      orgRole: <PAGOPA_ORG_ROLE>
  organization_id: <TEST_ORGANIZATION_ID>
  merchants:
    merchant_1:
      id: <MERCHANT_ID_1>
      fiscal_code: <MERCHANT_FISCAL_CODE_1>
      iban: <MERCHANT_IBAN_1>
    merchant_2:
      id: <MERCHANT_ID_2>
      fiscal_code: <MERCHANT_FISCAL_CODE_2>
      iban: <MERCHANT_IBAN_2>
  idpay_code:
    public_encrypt_key: <PUBLIC_ENCRYPT_KEY>
    encrypt_key_test: <ENCRYPT_KEY_TEST>
