uat:
  mauth:
    cert_base64: <CSTAR_CERTIFICATE_BASE64>
    key_base64: <CSTAR_PRIVATE_KEY_BASE64>
  api_key:
    IDPAY_APP_ISSUER_PRODUCT: <API_KEY_ISSUER_UAT>
    RTD_API_Product: <API_KEY_RTD_UAT>
    RTD_Mock_API_Product: <API_KEY_RTD_MOCK_UAT>
  initiatives:
    not_started:
      id: <NOT_STARTED_ID>
    cashback_like:
      id: <CASHBACK_LIKE_ID>
    complex:
      id: <COMPLEX_ID>
    timeframes:
      id: <TIMEFRAMES_ID>
  pm:
    pub_key: <PM_PUBLIC_KEY>
  organization_id: <TEST_ORGANIZATION_ID>
