@Scontoditipo6
@transaction
Feature: A transaction is generated, authorized and confirmed

  Background:
    Given the initiative is "Scontoditipo6"
    And the citizen A is 20 years old at most
    And the citizen A is onboarded
    And the random merchant 1 is onboard

  Scenario: The transaction of amount 10000 cents, confirmed by the citizen creates the transaction of amount 8712 cents
    When the merchant 1 generates the transaction X of amount 10000 cents
    And the citizen A confirms the transaction X
    Then the citizen A is rewarded with 87.12 euros

  Scenario: The transaction of amount 1 cents confirmed by the citizen creates the transaction of amount 1 cents
    When the merchant 1 generates the transaction X of amount 1 cents
    And the citizen A confirms the transaction X
    Then the citizen A is rewarded with 0.01 euros

  Scenario: With transaction of amount 20000 cents, the citizen confirms within the available budget with
    When the merchant 1 generates the transaction X of amount 20000 cents
    And the citizen A confirms the transaction X
    Then the citizen A is rewarded with 99.9 euros

  Scenario: User cannot confirm a second transaction because the initiative is one shot type
    Given the merchant 1 generates the transaction X of amount 1000 cents
    And the citizen A confirms the transaction X
    When the merchant 1 generates the transaction Y of amount 1500 cents
    And the citizen A tries to confirm the transaction Y
    Then the transaction Y is not authorized

  Scenario: User, after not having authorized the first transaction, authorizes a second transaction
    Given the merchant 1 generates the transaction X of amount 1000 cents
    When the merchant 1 generates the transaction Y of amount 2000 cents
    And the citizen A confirms the transaction Y
    Then the transaction Y is authorized


  Scenario: Against two transactions generated by the same merchant the citizen, who confirms the first will receive error when confirming the second transaction
    Given the merchant 1 generates the transaction X of amount 1000 cents
    And the merchant 1 generates the transaction Y of amount 1500 cents
    And the citizen A confirms the transaction X
    When the citizen A tries to confirm the transaction Y
    Then the transaction Y is not authorized

  Scenario: Against two transactions generated by two merchants the citizen, who confirms the first will receive error when confirming the second transaction
    Given the random merchant 2 is onboard
    And the merchant 1 generates the transaction X of amount 1000 cents
    And the merchant 2 generates the transaction Y of amount 1500 cents
    And the citizen A confirms the transaction Y
    When the citizen A tries to confirm the transaction X
    Then the transaction X is not authorized
