name: test-run

permissions:
  id-token: write
  contents: write

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      feature:
        type: choice
        description: Run functional tests by tag
        required: false
        default: bonus_elettrodomestici
        options:
          - all
          - bonus_elettrodomestici
          - onboarding
          - transaction
          - cancellation
          - readmission
          - refunds
          - unsubscribe
          - family
          - bar_code
          - idpay_code
          - ranking

      environment:
        description: Environment
        required: false
        default: dev
        type: choice
        options:
          - dev
          - uat

      test_type:
        description: Test type to run
        required: false
        default: all
        type: choice
        options:
          - all
          - bdd
          - functional

jobs:
  run-bdd:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.test_type == 'all' || inputs.test_type == 'bdd' }}
    uses: ./.github/workflows/test-run-bdd.yaml
    with:
      target_env: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}
      feature_tag: ${{ github.event_name == 'workflow_dispatch' && inputs.feature || 'bonus_elettrodomestici' }}
    secrets: inherit

  run-functional-tests:
    needs: run-bdd
    if: ${{ always() && (github.event_name != 'workflow_dispatch' || inputs.test_type == 'all' || inputs.test_type == 'functional') }}
    uses: ./.github/workflows/test-run-functional-test.yaml
    with:
      target_env: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}
    secrets: inherit